name: Build Windows Executable with PyInstaller

# 触发工作流的事件
on:
  push:
    branches: [ win ]
  pull_request:
    branches: [ win ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build-windows:
    # 使用 Windows 运行环境
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8' # 保持用户指定的 Python 版本
          architecture: 'x64'

      # 安装依赖和 PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller
        shell: pwsh

      # 运行 PyInstaller 打包
      - name: Build executable
        run: |
          pyinstaller -y --clean -D -c -n wxdown-service --add-data=resources/credential.py:resources/ main.py
        shell: pwsh

      # 调试：列出 dist/ 目录内容
      - name: List dist directory
        run: |
          Get-ChildItem -Path dist -Recurse
        shell: pwsh

      # 压缩 dist/wxdown-service/ 为 wxdown-service.zip
      - name: Create zip archive
        run: |
          Compress-Archive -Path dist/wxdown-service/* -DestinationPath wxdown-service.zip
        shell: pwsh

      # 上传打包结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wxdown-service.zip
          path: wxdown-service.zip
          retention-days: 7
